steps:
# Download the model to embed it into the image
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r', 'gs://azenews-bucket/models/aze-ds-model-first', '.']
  id: 'download-model'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-azer-ds/aze-ds-vertex-predict', '.']
  waitFor: ['download-model']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-azer-ds/aze-ds-vertex-predict']

images:
- gcr.io/test-azer-ds/aze-ds-vertex-predict
